name: check clang-format
on:
  pull_request:
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    steps:
    - uses: actions/checkout@v2
    - name: Run clang-format style check.
      uses: DoozyX/clang-format-lint-action@v0.14
      with:
        source: '.'
        extensions: 'c,h'
        clangFormatVersion: 13
        style: file
