name: fabtsuite
on:
  workflow_dispatch:
  push:
    paths-ignore:
    - 'doc/**'
    - 'LICENSE'
    - '**.md'

jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      matrix:
        name: ["Ubuntu Latest GCC"]
        include:
          - name: "Ubuntu Latest GCC"
            artifact: "Linux.tar.xz"
            os: ubuntu-latest

    name: ${{ matrix.name }}
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
          
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Install Dependencies (Linux)
      run: |
        sudo apt-get update -y
        sudo apt-get install libfabric1
      if: matrix.os == 'ubuntu-latest'
    
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Get Sources
      uses: actions/checkout@v2

    - name: Checkout Spack
      uses: actions/checkout@v2
      with:
        repository: hyoklee/spack
        path: ./spack

    - name: Run a multi-line script
      run: |
        . ./spack/share/spack/setup-env.sh
        spack install libfabric
        spack load libfabric
        mkdir "${{ runner.workspace }}/build"
        cd "${{ runner.workspace }}/build"
        cmake -DCMAKE_INSTALL_PREFIX=. ..
        make
        make install
        ./scripts/run-suite localhost

