name: spack fabtsuite

on:
  push:
    branches: [ main ]
    paths-ignore:
    - 'doc/**'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Spack
      uses: actions/checkout@v2
      with:
        repository: hyoklee/spack
        path: ./spack

    - name: Run a multi-line script
      run: |
        . ./spack/share/spack/setup-env.sh
        spack install fabtsuite ^libfabric@1.15.1 fabrics=rxm,tcp,udp,rxd
        spack load fabtsuite
        env
        fabtget -b localhost &
        fabtput localhost
        fabtrun
	
